model:
  target: models.interpretable_diffusion.gaussian_diffusion.MLA_Diffusion
  params:
    seq_length: 1000
    feature_size: 12 
    n_layer_enc: 4
    n_layer_dec: 2
    d_model: 256  # 12 X 12
    timesteps: 500
    sampling_timesteps: 500
    loss_type: 'l2'
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0
    use_ff: True
    use_text: True
    text_encoder_url: "ncbi/MedCPT-Query-Encoder"

solver:
  base_lr: 1.0e-5
  max_steps: 500000
  results_folder: ./results/cond_text_syn/MIMIC
  gradient_accumulate_every: 1
  save_cycle: 50000  # max_steps // 10
  ema:
    decay: 0.995
    update_interval: 10
  
  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 2000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500 
      verbose: False
  use_text: True
  
dataloader:
  train_dataset:
    target: utils.data_utils.ecg_dataset.ECGDataset
    params:
      name: MIMIC
      data_root: ./data/datasets/MIMIC
      window: 1000  # seq_length
      save2npy: True
      auto_norm_type: None
      seed: 42
      period: train
      condition_type: cond
      use_text: True

  test_dataset:
    target: utils.data_utils.ecg_dataset.ECGDataset
    params:
      name: MIMIC
      data_root: ./data/datasets/MIMIC
      window: 1000  # seq_length
      save2npy: True
      auto_norm_type: None
      seed: 42
      period: test
      use_text: True
    coefficient: 1.0e-2
    step_size: 5.0e-2
    sampling_steps: 200

  batch_size: 64
  sample_size: 32
  shuffle: True
